### ISSUE TITLE
Error at the beginning of YOLOv8 training

### ISSUE THREAD

**Issue by denhikan** [ultralytics/hub#256]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Hello, an error occurs when trying to start training the YOLOv8 model. 
Error:

RuntimeError: Dataset 'https://storage.googleapis.com/ultralytics-hub.appspot.com/users/eIZldWaQtrMNd49rLwHOlXGKGO32/datasets/Y9CeFzt44r0wpIML0gSq/train_data3.zip' error ❌ 

I did "!pip install -U ultralytics". The error did not go away.”
![image](https://user-images.githubusercontent.com/91408162/235982882-41e2972a-5487-46ed-8416-dca94c1e6ff8.png)

**Comment by kalenmike** [comment]
@denhikan Thanks for taking the time to raise this issue. Looking at your dataset it looks like your YAML is not correct. You can see this line:

`path: ../datasets/train_data3 # dataset root dir (leave empty for HUB)`

You should delete this key or leave it empty and re-upload your dataset and the issue should be resolved.

**Comment by denhikan** [comment]
Changed yaml, the error did not disappear
model = YOLO('https://hub.ultralytics.com/models/5Vd7WjNjaCvkS7YzJscG')
model.train()
![image](https://user-images.githubusercontent.com/91408162/236121768-55a1090e-b23d-4d30-bee3-a7d23751335e.png)

**Comment by kalenmike** [comment]
@denhikan Ok I looked into this more and the issue is being caused by the names key. It is in the older YOLOv5 format. You can fix this by updating the names key to a dictionary.

```yaml
names: 
  0: "trafficlight"
  1: "stop"
  2: "speedlimit"
  3: "crosswalk"
```

*Spacing is important in YAML files.

@glenn-jocher Does YOLOv8 intentionally not support these older dataset formats?

**Comment by denhikan** [comment]
@kalenmike, I apologize, I changed the yaml, but it still doesn’t work… 
model = YOLO('https://hub.ultralytics.com/models/VkmxvQAZmdb48LWUISvW')
model.train()
![image](https://user-images.githubusercontent.com/91408162/236220669-43163ff5-5351-467e-83e8-3f50221722de.png)

model = YOLO('https://hub.ultralytics.com/models/zJ3EdONZnlVZSj1D8cJo')
model.train()
![image](https://user-images.githubusercontent.com/91408162/236220055-12159dc5-473f-401e-ac4c-3547c6914343.png)

**Comment by kalenmike** [comment]
@denhikan In your latest dataset you zipped the contents and not the folder. The zip should contain a folder and inside that folder the dataset.

We will look into getting YOLOv8 to handle both cases.
