### ISSUE TITLE
Problem resuming training in Google Colab (Continued)

### ISSUE THREAD

**Issue by sebasmej** [ultralytics/hub#674]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Training

### Bug

I am training a model using google colab and when I try to resume executing the commands:
```
%pip install ultralytics  # install
from ultralytics import YOLO, checks, hub
checks()  # checks

hub.login('my_API_KEY')
model = YOLO('my_MODEL_ID')
results = model.train()
```
the following error message appears:
```
Ultralytics HUB: New authentication successful ✅
Ultralytics HUB: View model at https://hub.ultralytics.com/models/6SUZnsAo0z0y6gld7lpp 🚀
Downloading https://storage.googleapis.com/ultralytics-hub.appspot.com/users/gR39oPibZKaU7n6mUI0WE1H1CQH2/models/6SUZnsAo0z0y6gld7lpp/epoch-32.pt to 'epoch-32.pt'...
⚠️ Download failure, retrying 1/3 https://storage.googleapis.com/ultralytics-hub.appspot.com/users/gR39oPibZKaU7n6mUI0WE1H1CQH2/models/6SUZnsAo0z0y6gld7lpp/epoch-32.pt?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=firebase-adminsdk-jsjt9%40ultralytics-hub.iam.gserviceaccount.com%2F20240502%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20240502T073319Z&X-Goog-Expires=900&X-Goog-SignedHeaders=host&X-Goog-Signature=1ec7aecb22b2a6b13261b8b0fc2ac3e0a11e1077edf9483536cedc8921e7a0ee992473b79b8e59a9ae1d8cdc46d6d6c4c78b0aeab0f7b5707f7cf3d797c5cab7f43e91666670df484c8a871b893088dd59ed8b5769a46b9b32670425c473a352033766e62ce291a547b5d597eab4b9bbfdcafd298eb1ed8d54f7c09a8b4e0e6979fe039d702a9606bb1c27bebfc9e41f67c4bb34de8efd35cfabc08630a390b73caa5b43c1fb663446fafc0971f404ab0f001a0c4f3b7ab128f44413d977e428423e438d7612a2bd310d1640cb87acd8f63aa327f781500564f56970abd173091acdd698191cbfc38f1980d36f2e32ac7da17d2fe3862447d3685070082273ea...
---------------------------------------------------------------------------
UnpicklingError                           Traceback (most recent call last)
<ipython-input-8-1b077e47cb44> in <cell line: 5>()
      3 
      4 # Load your model from HUB (replace 'YOUR_MODEL_ID' with your model ID)
----> 5 model = YOLO('https://hub.ultralytics.com/models/6SUZnsAo0z0y6gld7lpp')
      6 
      7 # Train the model

6 frames
/usr/local/lib/python3.10/dist-packages/torch/serialization.py in _legacy_load(f, map_location, pickle_module, **pickle_load_args)
   1256             "functionality.")
   1257 
-> 1258     magic_number = pickle_module.load(f, **pickle_load_args)
   1259     if magic_number != MAGIC_NUMBER:
   1260         raise RuntimeError("Invalid magic number; corrupt file?")

UnpicklingError: invalid load key, '<'.
```

I follow your recomendations to solve this issue, I Rerun the Training Cell, Check Internet Connection and Clear Colab Environment. but the issue persits. For further investigation i append details of the error after rerun:
```
Ultralytics HUB: New authentication successful ✅
Ultralytics HUB: View model at https://hub.ultralytics.com/models/6SUZnsAo0z0y6gld7lpp 🚀
Found https://storage.googleapis.com/ultralytics-hub.appspot.com/users/gR39oPibZKaU7n6mUI0WE1H1CQH2/models/6SUZnsAo0z0y6gld7lpp/epoch-32.pt locally at epoch-32.pt
---------------------------------------------------------------------------
UnpicklingError                           Traceback (most recent call last)
<ipython-input-9-1b077e47cb44> in <cell line: 5>()
      3 
      4 # Load your model from HUB (replace 'YOUR_MODEL_ID' with your model ID)
----> 5 model = YOLO('https://hub.ultralytics.com/models/6SUZnsAo0z0y6gld7lpp')
      6 
      7 # Train the model

6 frames
/usr/local/lib/python3.10/dist-packages/ultralytics/models/yolo/model.py in __init__(self, model, task, verbose)
     21         else:
     22             # Continue with default YOLO initialization
---> 23             super().__init__(model=model, task=task, verbose=verbose)
     24 
     25     @property

/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py in __init__(self, model, task, verbose)
    149             self._new(model, task=task, verbose=verbose)
    150         else:
--> 151             self._load(model, task=task)
    152 
    153     def __call__(

/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py in _load(self, weights, task)
    238 
    239         if Path(weights).suffix == ".pt":
--> 240             self.model, self.ckpt = attempt_load_one_weight(weights)
    241             self.task = self.model.args["task"]
    242             self.overrides = self.model.args = self._reset_ckpt_args(self.model.args)

/usr/local/lib/python3.10/dist-packages/ultralytics/nn/tasks.py in attempt_load_one_weight(weight, device, inplace, fuse)
    804 def attempt_load_one_weight(weight, device=None, inplace=True, fuse=False):
    805     """Loads a single model weights."""
--> 806     ckpt, weight = torch_safe_load(weight)  # load ckpt
    807     args = {**DEFAULT_CFG_DICT, **(ckpt.get("train_args", {}))}  # combine model and default args, preferring model args
    808     model = (ckpt.get("ema") or ckpt["model"]).to(device).float()  # FP32 model

/usr/local/lib/python3.10/dist-packages/ultralytics/nn/tasks.py in torch_safe_load(weight)
    730             }
    731         ):  # for legacy 8.0 Classify and Pose models
--> 732             ckpt = torch.load(file, map_location="cpu")
    733 
    734     except ModuleNotFoundError as e:  # e.name is missing module name

/usr/local/lib/python3.10/dist-packages/torch/serialization.py in load(f, map_location, pickle_module, weights_only, mmap, **pickle_load_args)
   1038             except RuntimeError as e:
   1039                 raise pickle.UnpicklingError(UNSAFE_MESSAGE + str(e)) from None
-> 1040         return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
   1041 
   1042 

/usr/local/lib/python3.10/dist-packages/torch/serialization.py in _legacy_load(f, map_location, pickle_module, **pickle_load_args)
   1256             "functionality.")
   1257 
-> 1258     magic_number = pickle_module.load(f, **pickle_load_args)
   1259     if magic_number != MAGIC_NUMBER:
   1260         raise RuntimeError("Invalid magic number; corrupt file?")

UnpicklingError: invalid load key, '<'.
```

### Environment

Google Colab

### Minimal Reproducible Example

1. Login to hub
2. Search the model to train
3. Click to copy the Colab code
4. Run First Google Colab cell
5. Run Second Google Colab cell
6. Error appears
7. Rerun Second Google Colab cell
8.  Second Error appears

**Comment by pderrenger** [comment]
Hello! 👋 It seems the issue you're encountering is related to the download or loading of the model's checkpoint file. The error message you're seeing (`UnpicklingError: invalid load key, '<'.`) suggests that the downloaded file might be corrupted or not a valid `.pt` file. This can sometimes occur due to incomplete downloads or network issues.

As you've already tried the recommended steps (re-running the cell, checking internet connection, and clearing the Colab environment), you could try the following additional step to ensure the `.pt` file is fully and correctly downloaded:

1. **Manually download the checkpoint file**: Use the link provided in the error message or locate the direct download link for the `.pt` file from the Ultralytics HUB website. You can do this in a browser or through a programmatic method in Colab. Once downloaded, make sure the file size looks correct (not significantly smaller than expected).

2. **Upload the `.pt` file to your Colab environment**: You can use the Colab file upload feature to upload the `.pt` file directly into the Colab file system.

3. **Directly load the uploaded `.pt` file in your script**: Instead of using the model ID or download URL, point to the locally uploaded `.pt` file when loading the model.

If the problem persists even after these steps, it's possible there may be an issue with the `.pt` file itself. For further assistance, providing detailed information about the file size and exact steps you've taken could help in diagnosing the issue.

Remember to check the Ultralytics HUB Docs at https://docs.ultralytics.com/hub for more detailed instructions and troubleshooting tips. Your feedback is valuable, and the Ultralytics team appreciates your community involvement. Let's work together to solve this issue! 🚀

**Comment by sebasmej** [comment]
thanks for the answer I tried to download the file manually as you recommended. But when I try to download it with [the link that is in the error message] (https://storage.googleapis.com/ultralytics-hub.appspot.com/users/gR39oPibZKaU7n6mUI0WE1H1CQH2/models/6SUZnsAo0z0y6gld7lpp/epoch-32.pt) the following message appears:
```
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object. Permission 'storage.objects.get' denied on resource (or it may not exist).</Details>
</Error>
```
I am encountering problems with permissions, I am not sure how to authenticate, could you please help me to properly access the resources to manually download the .pt file.

This also happens if i try downloading it with the second link provided on the message error (https://storage.googleapis.com/ultralytics-hub.appspot.com/users/gR39oPibZKaU7n6mUI0WE1H1CQH2/models/6SUZnsAo0z0y6gld7lpp/epoch-32.pt?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=firebase-adminsdk-jsjt9%40ultralytics-hub.iam.gserviceaccount.com%2F20240503%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20240503T082307Z&X-Goog-Expires=900&X-Goog-SignedHeaders=host&X-Goog-Signature=61d4b243926debc55bdba0bfc6e849b6eea5e290fdb2cf3b0a8965f92c6fe9e8b76932ddff03ac95e779de05746b764a33274653d40fa967677e4d64cc167751d360b739df1c4ca19286956364c4b104f898ce2c36d79cbe699a9899f18b2ee968381e2cb85c1a48acd3d8f998fc60cfebd5ade7e210f4d053335b43e39fdfa5e77e70087160a066f9323a61aa962c90bf419a854a8bb7deccfc9ab5cdc3a78c9f2d5518edd24a4bab5864d0d64e26049820359fe910aae8aa1e8f5c6c2c5172c7067057e0d40375a64c1efa84d733f7c582e30996fe154c6c65e08cbd3eed28ebe8fcd43c77de1471cefcab353b7a2b729047789716b0abe5bca6e6107effea...
) the following message appears:
</Error>
```
<Error>
<Code>ExpiredToken</Code>
<Message>Invalid argument.</Message>
<Details>The provided token has expired. Request signature expired at: 2024-05-03T08:38:07+00:00</Details>
</Error>
```

**Comment by pderrenger** [comment]
Hey there! 👋 It looks like you're encountering access issues due to permission settings or an expired token for the `.pt` file. For security reasons, direct access to the download URLs typically requires authentication that matches the credentials permitted in our system.

For downloading model checkpoints from the Ultralytics HUB, I recommend ensuring that you're logged into the hub using the `hub.login('your_API_KEY')` method within your script. This should prevent the 'Access Denied' error by authenticating your access.

Regarding the expired token in the second URL, this usually occurs because URLs with embedded credentials have a short validity period for security reasons. To resolve this, it's best to generate a fresh download URL by re-initiating your session or request immediately before you plan to download the file.

If these steps don't resolve the issue, I'd suggest reaching out through our support channels with specifics (while avoiding sharing sensitive information like API keys publicly), so we can ensure proper access on your account.

Let's get this sorted! 🚀

**Comment by sergiuwaxmann** [comment]
@sebasmej We just checked and everything is working fine when starting/resuming training in Google Colab. Do you still have the issues above?

**Comment by sebasmej** [comment]
Yes, the problem persists. I have not been able to resume training, I am encountering the same errors I mentioned before.

**Comment by sergiuwaxmann** [comment]
@sebasmej

I’ve reviewed your model, and it appears there was indeed a hiccup with uploading the checkpoint for epoch 32. As a temporary measure, I’ve reverted the checkpoint to epoch 31 (previous successful checkpoint upload), which should allow you to resume training immediately. Could you please confirm if everything is back on track on your end?

Additionally, I’ve documented this incident with our development team to investigate further and ensure a permanent fix is implemented. This will help prevent such issues from recurring in the future.

PS If the error still occurs, maybe consider starting the training again (new model).

**Comment by sebasmej** [comment]
Thank you for your prompt reply. Yes everything is working fine now. I was able to continue the model training from epoch 31 without any problem.

**Comment by sergiuwaxmann** [comment]
@sebasmej I am glad your issue was solved. Thank you for you patience!
Hopefully, our team can implement a permanent fix soon as well.

**Comment by vwyLss** [comment]
@sergiuwaxmann I am having the same issue. I tried to manually download the checkpoint and its size is just 1kb. Could you revert my checkpoint to a previous successful checkpoint? Thanks in advance

My model ID: https://hub.ultralytics.com/models/ung87rRVHYHU5Wrhmq8p?tab=train

**Comment by sergiuwaxmann** [comment]
@vwyLss Can you check now? Last checkpoint should be epoch 125.

**Comment by vwyLss** [comment]
@sergiuwaxmann It is working now, thanks!

**Comment by marshaniswah** [comment]
@sergiuwaxmann Hello! I'm still encountering the same issue. Could you please revert my model to a previous successful checkpoint? Thank you very much!

My model: https://hub.ultralytics.com/models/LMEhtucmCZk4XUTeUjWD

**Comment by sergiuwaxmann** [comment]
@marshaniswah I’ve reverted the checkpoint to epoch 77 (previous successful checkpoint upload), which should allow you to resume training immediately. Could you please confirm if training is working again?

**Comment by marshaniswah** [comment]
Yeah, its working now. Im training the model right now. Thanks !

**Comment by joseabraham** [comment]
@sergiuwaxmann  Hello, I'm encountering the same issue. Could you please revert my model to a previous successful checkpoint? Thanks in advance:

Mode: https://hub.ultralytics.com/models/9nVppEnRgfYxE9aGROjl

**Comment by sergiuwaxmann** [comment]
@joseabraham Hello!
Sure, I replied to your issue: https://github.com/ultralytics/hub/issues/940.

**Comment by bcastagna1** [comment]
Hello @sergiuwaxmann. I'm running into the same issue as the above. In the Hub it's showing 100% with last checkpoint saved for epoch 299 (of 300). Would you be able to perform the same fix for me?

I dug into the locally saved weights/epoch-299.pt and I'm seeing the file showing the "NoSuchKey" error. I'm running everything on a custom agent.

Model URL: https://hub.ultralytics.com/models/ZgZqmopBn22vCOEzBrUS

Thank you!!

**Comment by sergiuwaxmann** [comment]
@bcastagna1 I’ve reverted the checkpoint to epoch 137 (previous successful checkpoint upload), which should allow you to resume training immediately.

**Comment by bcastagna1** [comment]
Thank you @sergiuwaxmann !

**Comment by KonDan2310** [comment]
@sergiuwaxmann Hi, I also have the same problem. Could you please revert my model to the previous checkpoint? Thanks in advance for your help:
My model: https://hub.ultralytics.com/models/g1kGF9foy7xBjFHMU0gz

**Comment by sergiuwaxmann** [comment]
@KonDan2310 I’ve reverted the checkpoint to epoch 75 (previous successful checkpoint upload), which should allow you to resume training immediately.

**Comment by KonDan2310** [comment]
Thanks for your help

**Comment by pderrenger** [comment]
You're welcome! 😊 If you encounter any further issues or have additional questions, feel free to ask. Happy training and best of luck with your project! 🚀

**Comment by JeyyGit** [comment]
@sergiuwaxmann Hi, I'm also experiencing the same problem of invalid access in the last checkpoint. My model is on https://hub.ultralytics.com/models/jMukkhZsXqg9cSXu75uk

**Comment by sergiuwaxmann** [comment]
@JeyyGit I’ve reverted the checkpoint to epoch 41 (previous successful checkpoint upload), which should allow you to resume training immediately.

**Comment by JeyyGit** [comment]
Thank you very much for the help @sergiuwaxmann!

**Comment by sergiuwaxmann** [comment]
@JeyyGit No worries!

**Comment by Clement-Tapway** [comment]
hi @sergiuwaxmann , same issue here, could you help me revert to epoch 178 🙏 
model link: https://hub.ultralytics.com/models/GVRXdYtcQuW6q2Xk0s7d

**Comment by sergiuwaxmann** [comment]
@Clement-Tapway Hello!
You should be able to resume training now from epoch 215.

**Comment by Clement-Tapway** [comment]
> [@Clement-Tapway](https://github.com/Clement-Tapway) Hello! You should be able to resume training now from epoch 215.

Thank you so much @sergiuwaxmann for the swift support!! 💪

**Comment by sergiuwaxmann** [comment]
@Clement-Tapway No worries! 🚀

**Comment by c0ngstar** [comment]
@sergiuwaxmann 
Hey! I face the same issue on the following model: https://hub.ultralytics.com/models/AyYH5SmwaC7UfYPYzJbS
I'd appreciate any help! Thanks in advance

**Comment by sergiuwaxmann** [comment]
@c0ngstar Hello!
You should be able to resume training now from epoch 49.

**Comment by c0ngstar** [comment]
Thank you very much! @sergiuwaxmann

**Comment by sergiuwaxmann** [comment]
@c0ngstar No worries! 🚀

**Comment by yogendrasinghx** [comment]
@nandanficode Thanks for sharing the model ID. I’ll take a look and get back to you!

**Comment by nandanficode** [comment]
can you help with this? @rahathasan452

**Comment by nandanficode** [comment]
@sergiuwaxmann can you please help with this?

**Comment by yogendrasinghx** [comment]
@nandanficode Sure. I'll take a look.

**Comment by yogendrasinghx** [comment]
Hi @nandanficode,

I’ve restored your training for [OXhti0op08jiIRQ8dABe](https://hub.ultralytics.com/models/OXhti0op08jiIRQ8dABe) to epoch 239. You should be able to resume training now without issues.

Let me know if you run into any further problems! 🚀

**Comment by nandanficode** [comment]
Thanks @yogendrasinghx.

**Comment by nandanficode** [comment]
@yogendrasinghx can you please help me with this one also
https://hub.ultralytics.com/models/b5WYG9E2ajI0Zp6kZ1Ew

**Comment by yogendrasinghx** [comment]
@nandanficode Sure. I'll take a look.

**Comment by nandanficode** [comment]
@yogendrasinghx thank you. Yes I am able to restart it. But here's a another model I faced the issue.
https://hub.ultralytics.com/models/DfVDMspFe5epDr5FuaIi
Is there a way I can handle it from my end as I am facing this issue more often

**Comment by nandanficode** [comment]
@yogendrasinghx can you please help me with this one also
https://hub.ultralytics.com/models/lznv05ngRBeS9UQCypON

**Comment by nandanficode** [comment]
@yogendrasinghx can you please help me with this one also
https://hub.ultralytics.com/models/lznv05ngRBeS9UQCypON

**Comment by Syar-tech** [comment]
Hello, 
I'm experiencing the same problem with the model [9V70JiFTFnlCmM2xaVqU](https://hub.ultralytics.com/models/9V70JiFTFnlCmM2xaVqU). Can you help me too with this one ?

**Comment by pderrenger** [comment]
Hi @Syar-tech — thanks for the report and the model link.

That UnpicklingError: invalid load key, '<' almost always means the local checkpoint file is actually an HTML error page or a partially downloaded file (often due to a signed URL expiring or a network interruption in Colab). When that happens, YOLO sees “Found … locally” and tries to load the corrupted file again.

Please try this quick reset in Colab, then resume:

1) Update packages and restart runtime
- %pip install -U ultralytics hub-sdk
- Runtime > Restart runtime

2) Clear any partially downloaded checkpoints
- This removes both stray epoch-*.pt files in the working directory and the HUB cache for your model.
- Replace the model ID below with yours if needed.

from pathlib import Path
import os, glob, shutil
from ultralytics.utils import SETTINGS

# Remove any local epoch checkpoints saved in the notebook directory
for f in glob.glob("epoch-*.pt"):
    try:
        os.remove(f)
    except FileNotFoundError:
        pass

# Remove HUB cache for this model to force a clean re-download
hub_cache = Path(SETTINGS["weights_dir"]) / "hub" / "9V70JiFTFnlCmM2xaVqU"
shutil.rmtree(hub_cache, ignore_errors=True)

3) Re-auth and resume from HUB

from ultralytics import hub, YOLO
hub.login("YOUR_API_KEY")
model = YOLO("https://hub.ultralytics.com/models/9V70JiFTFnlCmM2xaVqU")
results = model.train()  # uses HUB training args automatically

A few notes:
- It’s expected to see “using HUB training arguments, ignoring local training arguments.” The HUB session provides the correct resume configuration, so you don’t need to pass extra kwargs. See the train method behavior in the Ultralytics code reference for details: Reference for engine/model.train. See the Ultralytics Docs for details.
- If you see “Found … locally at epoch-XX.pt” again, make sure that file was deleted before retrying.
- For background, the HUB session loads weights via a signed URL during model initialization; if a download is interrupted or expired, the local file may be HTML or incomplete, which triggers the UnpicklingError. See how HUBTrainingSession.load_model fetches weights in the reference: Reference for HUBTrainingSession.load_model.

I’ve asked our team to run a checkpoint restore on 9V70JiFTFnlCmM2xaVqU as well, similar to earlier restores in this thread. We’ll update here once that’s complete. In the meantime, the steps above usually resolve this immediately in Colab.

If the issue persists after a clean reset:
- Share the full console log around the “Downloading/Found … epoch-*.pt” lines
- Print versions:
  - import ultralytics, hub_sdk; print(ultralytics.__version__, hub_sdk.__version__)
- Confirm your network is stable during the first load after restart

For general guidance on starting/resuming via the model page, see the Ultralytics HUB Models guide.

**Comment by nandanficode** [comment]
@yogendrasinghx can you please help with this one 
https://hub.ultralytics.com/models/Pr0vM8DR8eIpwVAwTVHk
The progress shows 100% but it is not available to download.
Further getting the same error while trying to resume.

**Comment by nandanficode** [comment]
@yogendrasinghx any updates?

**Comment by Clement-Tapway** [comment]
> [@Clement-Tapway](https://github.com/Clement-Tapway) Hey! You should be able to resume training from epoch `19`.

wow that's fast, thank you superman @sergiuwaxmann! 🦸
