### ISSUE TITLE
Ultralytics Hub IOS app not loading any private models if you're signed in to the App

### ISSUE THREAD

**Issue by ChrisTheCodingMaster** [ultralytics/hub#815]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

In the IOS app for Ultralytics hub and projects none of the private models load, the name of the model is present but it says no models are in the project and won't load. Yolov8 model selcetion also doesn't work if signed in. Datasets pages also doesn't load in the app. I also tried on another iphone one without beta software thinking thats the problem same issue. I even created a new account still doesn't work same issues.

### Environment

-iphone 12
-iphone 10

**Comment by glenn-jocher** [comment]
@ChrisTheCodingMaster hi there,

Thank you for bringing this to our attention and for providing detailed information about the issue you're experiencing with the Ultralytics iOS app. It sounds like there might be a bug affecting the loading of private models and datasets when signed in.

To help us investigate further, could you please ensure that you are using the latest version of the Ultralytics iOS app? Sometimes, issues are resolved in newer updates. If the problem persists even after updating, we would appreciate it if you could provide any additional details or steps that might help us reproduce the issue on our end.

In the meantime, you might find it helpful to check out our [Ultralytics iOS App Documentation](https://docs.ultralytics.com/hub/app/ios/) for any potential troubleshooting tips.

We appreciate your patience and understanding as we work to resolve this. If you have any more details or screenshots that could assist us, please feel free to share them here.

**Comment by ChrisTheCodingMaster** [comment]
After I reinstall the app, and I am signed in I am unable to access either yolov8 or 5 project folders as when I tap on them it doesn’t load. If I got to my private models the name is present but when I tap on it nothing load. But once I sign out of my account the yolov8 and 5 project folders loaded. This isn’t a problem with my account as I have created another account and had the same problem

**Comment by glenn-jocher** [comment]
Hi @ChrisTheCodingMaster,

Thank you for the additional details. It sounds like there might be an issue specific to the authentication process affecting the loading of your private models and project folders.

To help us pinpoint the problem, could you please try the following steps:

1. **Update the App**: Ensure you are using the latest version of the Ultralytics iOS app. Sometimes, updates contain fixes for issues like these.

2. **Clear Cache**: If the app has a cache-clearing option, try clearing the cache and then re-sign in to see if the issue persists.

3. **Network Connection**: Verify that you have a stable internet connection, as connectivity issues can sometimes cause loading problems.

4. **Reproduce the Issue**: If possible, try to reproduce the issue on a different network or device to rule out any network-specific problems.

If the issue continues even after these steps, it would be helpful if you could provide any error messages or logs that appear when you attempt to load the models or project folders. This information can be invaluable for our development team to diagnose and fix the issue.

We appreciate your patience and cooperation as we work to resolve this. Your feedback is crucial in helping us improve the app. If you have any more details or observations, please feel free to share them here.

Thank you! 😊

**Comment by ChrisTheCodingMaster** [comment]
1. I am on the latest iOS app update already
2.  The app doesn’t seem to have a clear cache option 
3. I have stable network and also tried on a different network same issue persists
4. I have used different accounts to see if I have the same issue if signed in models don’t load and signed out they do. I tried on a different iPhone same issue is present.

this seems to be an app issue as datasets page also doesn’t load 
![Uploading IMG_1399.png…](
![IMG_1397](https://github.com/user-attachments/assets/2724b828-ded6-4ae6-a57d-75d80c11b2ce)

**Comment by glenn-jocher** [comment]
Hi @ChrisTheCodingMaster,

Thank you for the detailed follow-up and for trying out the suggested steps. It does indeed sound like there might be an issue with the app itself, especially since you've confirmed the problem persists across different networks, devices, and accounts.

To help our development team investigate this further, could you please provide the following additional information:
1. **App Version**: The exact version of the Ultralytics iOS app you are using.
2. **iOS Version**: The iOS version installed on your devices.
3. **Screenshots**: Any error messages or logs that appear when you attempt to load the models or datasets.

Your screenshots and detailed observations are very helpful. If possible, please also include any specific steps you take that lead to the issue, as this can help us reproduce the problem more effectively.

We appreciate your patience and understanding as we work to resolve this. Your feedback is invaluable in helping us improve the app experience for everyone. If you have any more details or observations, please feel free to share them here.

Thank you for your cooperation! 😊

**Comment by ChrisTheCodingMaster** [comment]
1. IOS app version Version 0.9.23 (923)
2. iOS versions beta 18 , and iOS 17.5 on an another device.
![IMG_1399](https://github.com/user-attachments/assets/8119af60-701f-466e-8882-4c52c2d1ebc2)
![IMG_1397](https://github.com/user-attachments/assets/dc1d37fc-75ae-464a-b780-e2dae421b8f8)
![IMG_1398](https://github.com/user-attachments/assets/ce319174-3349-4ceb-b1cf-43fe07e253cb)

once I download the app and I’m not signed in I am able to access yolo model download page. Once I sign in yolo models not loading and same for private models same error in two devices and two accounts. The datasets page also seems broken which could mean app isn’t functioning properly.

**Comment by glenn-jocher** [comment]
Hi @ChrisTheCodingMaster,

Thank you for providing the detailed information and screenshots. It’s clear that you’ve encountered a reproducible issue with the Ultralytics iOS app, and we appreciate your thorough testing across different devices and accounts.

Given that you are using the latest app version (0.9.23) and have tested on both iOS beta 18 and iOS 17.5, it seems there might be a bug affecting the app's functionality when signed in.

To proceed, I recommend the following steps:

1. **Reinstall the App**: Although you've already tried this, sometimes a fresh reinstall can help. Ensure you completely remove the app before reinstalling it from the App Store.

2. **Check for Updates**: Occasionally, new updates are released that address such issues. Please keep an eye on the App Store for any new updates to the Ultralytics app.

3. **Report the Issue**: Since this appears to be a bug, I recommend reporting it directly to our development team through the [Ultralytics HUB GitHub Issues page](https://github.com/ultralytics/hub/issues). Include all the details you've provided here, as well as any additional observations.

In the meantime, you can continue to use the app without signing in to access the YOLO model download page. We understand this is not an ideal solution, but it may serve as a temporary workaround.

Thank you for your patience and for helping us improve the Ultralytics iOS app. If you have any further questions or need additional assistance, please feel free to reach out here.

**Comment by ChrisTheCodingMaster** [comment]
I'm not really sure how to report directly to your development team, do i just issue another bug report but include all the details i have already reported?

**Comment by glenn-jocher** [comment]
Hi @ChrisTheCodingMaster,

Thank you for your question and for your patience as we work through this issue together. Yes, you can report this directly to our development team by creating a new issue on the [Ultralytics HUB GitHub Issues page](https://github.com/ultralytics/hub/issues). When you do so, please include all the details you've already provided here, such as:

1. **App Version**: Version 0.9.23 (923)
2. **iOS Versions**: iOS beta 18 and iOS 17.5
3. **Detailed Description**: Explain the issue with private models and datasets not loading when signed in, and how they load when signed out.
4. **Screenshots**: Attach the screenshots you've shared here to help illustrate the problem.
5. **Steps to Reproduce**: Clearly outline the steps you take that lead to the issue.

This will help our development team to reproduce the issue and work on a fix more efficiently. We appreciate your cooperation and detailed reporting, which is invaluable in improving the app for everyone.

If you have any further questions or need additional assistance, feel free to ask here. We're here to help! 😊

Thank you again for your support and understanding.

**Comment by dingniaoji** [comment]
I think if you can make the `transfer` method work as expected in `models` page, the problem will be solved.

But it may be a busssiness concern or it is just a `bug`?

**Comment by glenn-jocher** [comment]
Hi there,

Thank you for your comment! It sounds like you're experiencing an issue with the `transfer` method on the models page. To help us address this, could you please verify if the issue persists in the latest version of the app? Sometimes updates contain important fixes.

If it’s a bug, we'll work on resolving it as soon as possible. However, if it’s related to business logic, it might require a different approach. Your feedback is invaluable, so please feel free to provide any additional details or steps to reproduce the issue.

We appreciate your understanding and support! 😊

If you have more questions or need further assistance, feel free to ask.

**Comment by dingniaoji** [comment]
[here is the more detailed disscusion](https://github.com/ultralytics/hub/issues/833)

I hope it is a `bug`, not a `bussiness concern`. :)

**Comment by glenn-jocher** [comment]
Hi there,

Thank you for sharing the detailed discussion link! 😊

If this is a bug, we definitely want to address it. Please ensure you're using the latest version of the app, as updates often contain important fixes. If the issue persists, providing any additional details or steps to reproduce the problem in the GitHub issue will be incredibly helpful for our team.

We appreciate your engagement and feedback. If you have any more questions or need further assistance, feel free to reach out here. We're here to help!

Thank you!

**Comment by yogendrasinghx** [comment]
@ChrisTheCodingMaster Thank you for your patience and for all the detailed information you've provided. We’ve released an update to the app, version `0.9.26`, which addresses issues with model and dataset loading on iOS. This should resolve the problem with private models and datasets not appearing when signed in.

Please update to version `0.9.26`. If the issue persists, try signing out, then uninstalling and reinstalling the app for a fresh setup. Your feedback has been instrumental in helping us identify and fix this issue. Thank you for your support—please let us know if you need further assistance!
